Initial scaffolding for store orders page
acmucsd/membership-portal-ui-v2 pull request #100
Opened 2023-12-28 22:57 UTC by alexzhang1618

# Description

What changes did you make? List all distinct problems that this PR addresses. Explain any relevant
motivation or context.

Initial code for store orders page in, putting in layout and filtering for full page.
In a follow up PR I'll add in viewing the info of a particular order and other order flow stuff.

## Changes
- fix some Typography sizes
- Implement OrderCard
- Implement OrdersDisplay
- Add a new API call to get all orders for the current user
- Add greater date util functions in utils.ts (allowing for the year to also be added in the format)
  - This will also be useful down the line for past event displays
- Implement Orders Page and dropdown for time filtering of orders
- Fix/add some colors that were needed in vars.scss

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally on Desktop.
- [x] locally on mobile - use https://ngrok.io to get a copy on a mobile device
- [x] on the live deployment preview on Desktop.
- [x] on the live deployment preview on Mobile.
- [ ] I have run and passed all new and existing Cypress tests. Add screenshots below.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have documented my code's `src/lib` functions and commented hard to understand areas
      anywhere else.
- [x] My changes produce no new warnings.

# Screenshots

<img width="1431" alt="Screenshot 2023-12-28 at 2 56 42 PM" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/27360825/19d4de6b-3a4e-4e54-bdc9-6d25d68308d9">
<img width="1431" alt="Screenshot 2023-12-28 at 2 56 52 PM" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/27360825/74a8d8fe-6652-4612-b6a5-07187f126419">
<img width="323" alt="Screenshot 2023-12-28 at 2 57 22 PM" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/27360825/09b9d525-74a8-4df4-b68b-d96b0c8c61c7">

2023-12-28 23:23 UTC, farisashai requested changes
Initial code review, haven't looked at a preview

2023-12-28 23:23 UTC, farisashai commented on src/components/store/OrderCard/index.tsx
> +const orderStatusName: { [_ in OrderStatus]: string } = {
There's a file for enums that is probably a better place to define these and easier to use

2023-12-28 23:23 UTC, farisashai commented on src/lib/api/StoreAPI.ts
>  /* eslint-disable import/prefer-default-export */
You should be able to delete this now that there are two exports

2023-12-28 23:23 UTC, farisashai commented on src/lib/api/StoreAPI.ts
> +import {
```suggestion
import type {
```

2023-12-28 23:23 UTC, farisashai commented on src/pages/store/orders.tsx
> +import OrdersDisplay from '@/components/store/OrdersDisplay';
```suggestion
import { OrdersDisplay } from '@/components/store';
```

2023-12-28 23:32 UTC, alexzhang1618 commented on src/components/store/OrderCard/index.tsx
> +const orderStatusName: { [_ in OrderStatus]: string } = {
I'll move the name map over, but I think we should keep the color map here since it's only relevant to the card and needs access to `styles`

2023-12-30 05:01 UTC, farisashai approved these changes
small feedback but looks good for now. When the page is more finalized I'll review the actual UI

2023-12-30 05:01 UTC, farisashai commented on src/lib/types/enums.ts
> +export const orderStatusName: { [_ in OrderStatus]: string } = {
on second thought, I did not realize that this was just a mapping for the labels. Probably doesn't need to be here oops 🫣🫣

question: can you not rely on implicit type assignment for this constant? the type signature seems unnecessary

2023-12-30 05:01 UTC, farisashai commented on src/components/store/OrdersDisplay/index.tsx
> +import OrderCard from '@/components/store/OrderCard';
Import from parent folder

2023-12-30 05:01 UTC, farisashai commented on src/pages/store/orders.tsx
> +import styles from '@/styles/pages/store/orders/index.module.scss';
```suggestion
import styles from '@/styles/pages/StoreOrders.module.scss';
```

this is maybe just a personal design preference but I don't see any reason for page CSS sheets to match the name of the page file, which has to be named to define the navigation route. I think it's easier for developers a tiny bit to work with

2023-12-30 05:05 UTC, alexzhang1618 commented on src/lib/types/enums.ts
> +export const orderStatusName: { [_ in OrderStatus]: string } = {
You can, but I like this a little better since it'll error loudly if new order statuses are added and it brings in autocomplete on VSCode

2023-12-30 05:09 UTC, alexzhang1618 commented on src/components/store/OrdersDisplay/index.tsx
> +import OrderCard from '@/components/store/OrderCard';
It turns out trying to import from the parent folder causes a dependency cycle that ESLint doesn't like, so I'll just add it as an export from index.ts and do a relative import here

2023-12-30 05:13 UTC, merged