Create Store Cart Page
acmucsd/membership-portal-ui-v2 pull request #116
Opened 2024-01-07 10:36 UTC by raymosun

# Info

Closes #57 

# Description

Implement the store cart page. Currently using regular events as placeholder pickup events until the link to events from pickup events is merged on backend.

## Changes

- Creates the Store Cart page at /store/cart

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [ x ] locally on Desktop.
- [ x ] locally on mobile - use https://ngrok.io to get a copy on a mobile device
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have run and passed all new and existing Cypress tests. Add screenshots below.

# Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have followed the style guidelines of this project.
- [ ] I have documented my code's `src/lib` functions and commented hard to understand areas
      anywhere else.
- [ ] My changes produce no new warnings.

# Screenshots

*Need to add more but need to set up a way to simulate a full cart

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/30709485/99e4ea99-17b7-45d9-add1-2a288bdffb49)

2024-01-07 23:41 UTC, farisashai requested changes
quick initial review

2024-01-07 23:41 UTC, farisashai commented on src/lib/api/StoreAPI.ts
> +  console.log(JSON.stringify(data));
Delete before merging

2024-01-07 23:41 UTC, farisashai commented on src/pages/store/cart.tsx
> +    setClientCookie('CART', clientCartToCookie(cart));
you should define this magic variable for cart in a variable in CookieType so it's consistent everywhere

2024-01-07 23:41 UTC, farisashai commented on src/pages/store/cart.tsx
> +    setClientCookie('CART', clientCartToCookie(cart));
I agree cookies are the best solution to store the cart but have you confirmed the implementation with Andy? I don't know if he's on the same page right now for the item page add to cart button

2024-01-07 23:41 UTC, farisashai commented on src/pages/store/cart.tsx
> +  const placeOrder = () =>
Move this function to StoreManager to separate out business logic from the component definition

2024-01-07 23:41 UTC, farisashai commented on src/pages/store/cart.tsx
> +            {tempFakeEvents[pickupIndex] && (
can you leave comments marked as TODO everywhere with temp code you want to replace in a future PR

2024-01-07 23:41 UTC, farisashai commented on src/styles/pages/store/cart/index.module.scss
> +          border: 0.0625rem solid var(--theme-accent-line-1-transparent);
I would just use pixels for anything below 0.5rem for clarity

2024-01-07 23:41 UTC, farisashai commented on src/styles/pages/store/cart/index.module.scss
> +      @media (max-width: vars.$breakpoint-md) {
```suggestion
      @media screen and (width < vars.$breakpoint-md) {
```

I want to try using a consistent syntax for all of the media queries in the repo

2024-01-07 23:41 UTC, farisashai commented on src/styles/pages/store/cart/index.module.scss
> +      border: 1px solid var(--theme-accent-line-2, #E4E4E4);
Seeking to learn: what is the hardcoded color for? the variable shouldn't be undefined ever unless there's a bug we need to fix

2024-01-07 23:41 UTC, farisashai commented on src/styles/pages/store/cart/index.module.scss
> +  max-width: 81rem;
is there a better value we can using that this? Maybe that's stored in a variable

2024-01-07 23:41 UTC, farisashai commented on src/pages/store/cart.tsx
> +      token: AUTH_TOKEN,
I commented this on Alex's PR too but you never need to pass the auth token through server side props because you can access the cookie directly on the client side browser

2024-01-07 23:41 UTC, farisashai commented on src/pages/store/cart.tsx
> +                - <Diamonds count={orderTotal} />
I don't think we need to render the minus if the cart is empty

2024-01-07 23:41 UTC, farisashai commented on src/lib/utils.ts
> +export const toSentenceCase = (str: string) => {
I think there's a capitalize function already from one of the other PRs we merged

2024-01-07 23:41 UTC, farisashai commented on src/components/store/StoreModal/index.tsx
> +          if (opener.props.onClick) opener.props.onClick();
```suggestion
opener?.props?.onClick();
```
 Can you test if this works the same?

2024-01-07 23:41 UTC, farisashai commented on src/components/store/StoreModal/index.tsx
> +      {cloneElement(opener, {
What does this do?

2024-01-07 23:41 UTC, farisashai commented on src/components/store/CartItemCard/index.tsx
> +import { UUID } from '@/lib/types';
```suggestion
import type { UUID } from '@/lib/types';
```

2024-01-19 06:43 UTC, raymosun commented
I'm not sure why the circleci linting is like out of sync with the Vercel linting

2024-01-31 07:08 UTC, closed without merging