added page to manage user access
acmucsd/membership-portal-ui-v2 pull request #137
Opened 2024-01-26 03:09 UTC by Stuart6557

# Info

Closes #136

[description]

Added a page that allows admins to update user access types.

## Changes

New page and API

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally on Desktop.
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have added new Cypress tests that are passing.

# Checklist

- [x] I have performed a self-review of my own code.
- [ ] I have followed the style guidelines of this project.
- [ ] I have documented any new functions in `/src/lib/*` and commented hard to understand areas
      anywhere else.
- [x] My changes produce no new warnings.

# Screenshots

<img width="1378" alt="image" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/85718304/b7e225cc-8ee4-4e2a-a4e7-5d33ad50591a">

2024-01-26 18:45 UTC, farisashai requested changes
excellent first PR - feature is working with good code quality. just a couple comments

2024-01-26 18:45 UTC, farisashai commented on .gitignore
let's revert this file since it's unrelated to the PR - this project isn't supposed to be using a .env file anyways. the development and production env files are already included here

2024-01-26 18:45 UTC, farisashai commented on .vscode/settings.json
same thing here with reverting the file, make sure you double check your diff in the PR before submitting reviewers because sometimes your editor will automatically make changes on your behalf that get included

2024-01-26 18:45 UTC, farisashai commented on src/lib/api/index.ts
> +export * as UserAccessAPI from './UserAccessAPI';
let's rename this to AdminAPI to encompass a broader set of admin specific portal actions - right now the name is too specific to the specific route you wrote here

2024-01-26 18:45 UTC, farisashai commented on src/lib/config.ts
> +        access: '/admin/access',
what is this route for? are we planning to have separate pages to view user access and mange it? I think ideally this should all be on a single page in a table UI eventually or something similar to view all users so since this hasn't been implemented yet, i think it makes more sense to include any view access functionality on the same manageUserAccess page

2024-01-26 18:45 UTC, farisashai commented on src/pages/admin/manage-user-access/index.tsx
> +        options={[
we don't want to hardcode these options here as magic variables - we have an enum defined in the constants folder I think for `UserAccessType` that you can map through to ensure the options are consistent across the portal

2024-01-26 18:45 UTC, farisashai commented on src/pages/admin/manage-user-access/index.tsx
> +        name="user access"
```suggestion
        name="User Access"
```

2024-01-26 18:45 UTC, farisashai commented on src/pages/admin/manage-user-access/index.tsx
> +        placeholder="User access"
we can delete this placeholder since there's a default selected option on initialization

2024-01-26 18:45 UTC, farisashai commented on src/pages/admin/manage-user-access/index.tsx
> +    try {
this try catch block should be in a manager function (see src/lib/managers/AuthManager file for an example) to separate client UI logic from business logic interacting with the API

2024-01-26 18:45 UTC, farisashai commented on src/pages/admin/manage-user-access/index.tsx
> +function reportError(title: string, error: unknown) {
if we're merging this directly into main can you leave a comment that this function needs to be moved to the util class after sean's PR is merged

2024-02-01 00:18 UTC, Stuart6557 commented on src/lib/config.ts
> +        access: '/admin/access',
this is an api endpoint, I used it in AdminAPI.ts

2024-02-01 00:21 UTC, Stuart6557 commented on src/pages/admin/manage-user-access/index.tsx
> +        placeholder="User access"
placeholder is required for SignInFormItem regardless of whether element is "input" or "select", should I change this in SignInFormItem?

2024-02-08 01:28 UTC, farisashai reviewed
backend is making a change where admin access levels can't be modified that will need to be reflected on this page too. You'll need to remove admin from the dropdown here when it's merged but we should hold off until then

2024-04-10 23:32 UTC, alexzhang1618 approved these changes
changes generally LGTM, let's get this up to date with main and merged in

2024-04-10 23:32 UTC, alexzhang1618 commented on src/lib/config.ts
> +    manageUserAccess: '/admin/manage-user-access',
can we just make this `/admin/access` to be consistent

2024-04-10 23:32 UTC, alexzhang1618 commented on src/pages/admin/manage-user-access/index.tsx
> +}
let's merge in main and use the `reportError` in utils

2024-04-25 04:08 UTC, farisashai approved these changes
i was waiting for https://github.com/acmucsd/membership-portal/pull/407 to merge first so we could implement the feature fully first go but we can do that in a separate PR if there's a hurry to make this available

2024-05-18 19:44 UTC, merged