new event card design
acmucsd/membership-portal-ui-v2 pull request #172
Opened 2024-03-12 03:13 UTC by SheepTester

# Info

Closes #162 

updated event card design

did not touch event details modal, so `PointsDisplay` and `CommunityLogo` are still in use

## Changes

- event card design
- I changed the `Community.AI` enum value to `Ai`. The enum was only used for `CommunityLogo`. There are two reasons for this
  - `CommunityLogo` currently uses `capitalize` to normalize ACM communities, but this would turn `AI` into `Ai`
  - For some reason, our `.scss.d.ts` generator turns `.badgeAI` into `.badgeAi`. I have no idea why

# Type of Change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally on Desktop.
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have added new Cypress tests that are passing.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have documented any new functions in `/src/lib/*` and commented hard to understand areas
      anywhere else.
- [x] My changes produce no new warnings.

# Screenshots

2024-03-12 03:18 UTC, alexzhang1618 requested changes
Contrast is a little rough on dark mode
<img width="336" alt="Screenshot 2024-03-11 at 8 17 54 PM" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/27360825/20c307e1-fac4-4f28-b981-04dd0793c183">

2024-03-12 03:21 UTC, alexzhang1618 commented
> Contrast is a little rough on dark mode <img alt="Screenshot 2024-03-11 at 8 17 54 PM" width="336" src="https://private-user-images.githubusercontent.com/27360825/311929018-20c307e1-fac4-4f28-b981-04dd0793c183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTM5MTcsIm5iZiI6MTcxMDIxMzYxNywicGF0aCI6Ii8yNzM2MDgyNS8zMTE5MjkwMTgtMjBjMzA3ZTEtZmFjNC00ZjI4LWI5ODEtMDRkZDA3OTNjMTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDAzMjAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzODlkYTVlYzZhMzliZmI2ZTc2NzQzY2NmNzZmYTJjYWM1NDFlNTVlZmVlYzZmN2Q5MzM5ZjQxNWI1NTY0N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lbUk069dCEcubWP-8xeZeyd18jt2RQunz0W-GdBEVFI">

Also, is it just me or is the spacing a little uneven between the event title, event location, and tags? Let's also remove the year when on the main dashboard as well since it should be evident that it's happening this year

2024-03-12 03:22 UTC, SheepTester commented
> Also, is it just me or is the spacing a little uneven between the event title, event location, and tags? Let's also remove the year when on the main dashboard as well since it should be evident that it's happening this year

the year is there because the event is a year long

2024-03-12 03:22 UTC, SheepTester commented
> ## Merge state

yeah i realized it has been fixed

2024-03-12 03:23 UTC, alexzhang1618 approved these changes
lgtm ship ship ship ship ship ship ship ship ship ship ship ship ship ship ship ship ship ship ship ship

2024-03-12 04:10 UTC, SheepTester commented
issue: pickup event on checkout page is cut off

2024-03-14 00:55 UTC, farisashai commented on src/components/common/CommunityLogo/index.tsx
> -    return <Image src={communityLogos.General} width={size} alt="ACM General Logo" />;
is this completely removing the fallback for an invalid enum value?

2024-03-14 00:55 UTC, farisashai commented on src/components/events/EventCard/index.tsx
> +              {!isOrderPickupEvent(event) && (
left a comment abt this syntax on a older PR. we should prefer `condition ? Component : null`

2024-03-14 18:44 UTC, SheepTester commented on src/components/common/CommunityLogo/index.tsx
> -    return <Image src={communityLogos.General} width={size} alt="ACM General Logo" />;
yes, because the fallback defaults to ACM General

2024-03-22 22:35 UTC, SheepTester commented
It shouldn't show any tags for unlinked events

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/b923cc83-bb3a-4cd0-8f44-97709220ac6f)

2024-03-25 18:57 UTC, merged