Prettier pagination
acmucsd/membership-portal-ui-v2 pull request #213
Opened 2024-03-31 22:46 UTC by alexzhang1618

# Info

Closes **[ISSUE NUMBER]**.

[description]

## Changes

- [Fill in here]

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [ ] locally on Desktop.
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have added new Cypress tests that are passing.

# Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have followed the style guidelines of this project.
- [ ] I have documented any new functions in `/src/lib/*` and commented hard to understand areas
      anywhere else.
- [ ] My changes produce no new warnings.

# Screenshots

2024-03-31 23:03 UTC, SheepTester requested changes
page numbers are broken on leaderboard:

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/b9a2dea4-73ec-4bf1-825e-e5ee03542d2d)


![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/b906c775-a2ef-44da-b71d-0754ec19c198)

Should we make the current number an input to still allow people to enter in a page number. like if they hover/focus on the blue number, the input reveals a border/background color

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/2efb9cc6-30d1-4032-a9b3-60e77dfd5b48)


Maybe it could show nothing if there's only one page

2024-03-31 23:03 UTC, SheepTester commented on src/components/common/PaginationControls/style.module.scss
>    .paginationBtn {
![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/5bf2cbc7-4c64-47eb-ad75-6109820a0c5a)

maybe you should make these a bit larger so they're the same size as the page numbers

2024-03-31 23:03 UTC, SheepTester commented on src/components/common/PaginationControls/index.tsx
> +  const start = Math.max(1, displayPage - radius);
i think you mean

```suggestion
  const start = Math.min(1, displayPage - radius);
```

2024-04-01 18:33 UTC, SheepTester commented on src/components/common/PaginationControls/style.module.scss
>    .paginationBtn {
actually nvm i like that it;s smaller

2024-04-13 19:37 UTC, alexzhang1618 commented
![Screenshot 2024-04-13 at 12 37 06 PM](https://github.com/acmucsd/membership-portal-ui-v2/assets/27360825/d47d2997-b4c2-428b-9ffd-4a040cb3d9f7)
Switching to a simpler, redesigned version of pagination

2024-04-13 20:32 UTC, SheepTester approved these changes
lgtm

2024-04-13 20:33 UTC, merged