Implement SEO
acmucsd/membership-portal-ui-v2 pull request #25
Opened 2023-04-13 21:32 UTC by raymosun

# Info

Closes #2 

# Description

What changes did you make? List all distinct problems that this PR addresses. Explain any relevant
motivation or context.

Adds SEO component with open graph and other metadata for link previews, etc.

## Changes

Added SEO component, used in page layout, to insert meta tags to page head.

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [ ] locally on Desktop.
- [ ] locally on mobile - use https://ngrok.io to get a copy on a mobile device
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have run and passed all new and existing Cypress tests. Add screenshots below.

# Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have followed the style guidelines of this project.
- [ ] I have documented my code's `src/lib` functions and commented hard to understand areas
      anywhere else.
- [ ] My changes produce no new warnings.

# Screenshots

Please include a screenshot of your Cypress testing suite passing successfully.

If you made any visual changes to the website, please include relevant screenshots below.

![image](https://user-images.githubusercontent.com/30709485/231887597-9f387aff-ccf3-477e-95f5-ec5fc4fa1dde.png)

2023-04-13 21:35 UTC, raymosun commented
Initial progress on SEO component. Some descriptions, etc. are placeholders.

2023-04-14 19:35 UTC, farisashai commented on src/components/layout/PageLayout/index.tsx
> +    <SEO />
Let's move this component to the `src/pages/_app.tsx` file for all technical components that aren't directly related to the UI layout.

2023-04-14 19:44 UTC, farisashai commented on src/components/common/SEO/index.tsx
> +  const DESC =
Updated description (open to suggestions)
`Meet new friends, discover exciting events, and earn points for free ACM swag! Create an account today to find your community!`

2023-04-14 19:56 UTC, farisashai commented on src/components/common/SEO/index.tsx
> +        content="https://cdn.discordapp.com/attachments/975657067031437332/1092620423281250335/Screenshot_2023-04-03_at_6.23.24_PM.jpg"
![Screenshot 2023-04-14 at 12 51 26 PM](https://user-images.githubusercontent.com/33165426/232142379-2644964c-3997-4134-a313-244cc9846d1e.jpg)

Let's keep this image just as the standard light mode ACM logo to match the style of the ACM main website link previews so its clean and legible.

2023-04-14 20:03 UTC, farisashai requested changes
Last comment is unrelated to the changes in your actual code but we should be prioritizing the performance, accessibility, and search engine optimizations on our website whenever we develop. We can only really test the login page in this project since the rest are authenticated but if you go to this website (https://pagespeed.web.dev/), it gives some good tips for general optimizations usually.

It will give us a score on each metric and some tips to improve them as you scroll below. When I compare the current version to your deployment preview, it looks like we bumped up the SEO successfully with no pending issues so good job with that 👏 

![Screenshot 2023-04-14 at 12 59 40 PM](https://user-images.githubusercontent.com/33165426/232143699-613f41bd-f28a-4cbb-8f25-6ef59c844cc8.jpg)

![Screenshot 2023-04-14 at 1 00 53 PM](https://user-images.githubusercontent.com/33165426/232143888-a3ca23d9-8f07-4c2a-888a-ba5e0bb3f245.jpg)


Using the deployment preview link in this PR, can you test it and see if you can address some of the accessibility issues we have right now?

2023-04-14 21:51 UTC, farisashai approved these changes
LGTM  🤑 🚀

2023-04-15 05:57 UTC, merged