about page with discord embed created; works with light dark toggle and mobile
acmucsd/membership-portal-ui-v2 pull request #48
Opened 2023-07-20 04:15 UTC by adahe8

# Info

Closes **39**, creating the about page.

# Description

This is the NextJS implementation of the about page for the ACM portal; I've added the discord embed and transferred the socials and descriptions over.

## Changes

Added discord embed, used currentColor CSS var to make the svg icons responsive to the toggle, replaced and updated some svg icons to slightly higher quality ones.

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally on Desktop.
- [x] locally on mobile - use https://ngrok.io to get a copy on a mobile device
- [x] on the live deployment preview on Desktop.
- [x] on the live deployment preview on Mobile.
- [ ] I have run and passed all new and existing Cypress tests. Add screenshots below.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have documented my code's `src/lib` functions and commented hard to understand areas
      anywhere else.
- [x] My changes produce no new warnings.

# Screenshots

Please include a screenshot of your Cypress testing suite passing successfully.

If you made any visual changes to the website, please include relevant screenshots below.

2023-07-24 02:57 UTC, raymosun requested changes
Hey, nice work on this! The discord embed fits in really nicely on this page.

I left a couple comments for you on code. Additionally,
1. Can you center the content on the page, probably by putting all the content in a container with a max-width and `margin: 0 auto`. Maybe you can reference Leaderboard, the only other completed page so we can have consistent styling for this.
2. Small thing, but I noticed the corners of the discord embed inside the border radius remain white in dark mode. Could you look into having this match the theme as well please :) 
![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/30709485/60d09c40-8bc4-4dfb-8ca3-74c7fc3917ca)

2023-07-24 02:57 UTC, raymosun commented on src/lib/config.ts
> +          this portal or following us on social media!`,
Since this description is only used on one page, it's better to keep it with the About page's files.

2023-07-24 02:57 UTC, raymosun commented on src/pages/about.tsx
> +import logo from '@/public/assets/acm-logos/general/light-mode.png';
Nit: maybe name this something like `AcmLogo` to keep it unambiguous and in line with other icon names

2023-07-24 02:57 UTC, raymosun commented on src/styles/pages/about.module.scss
> +  @media only screen and (min-width: 700px) {
In `vars.scss` we have some breakpoint size variables that could be used here. They help keep the site consistent across pages.

2023-07-24 02:57 UTC, raymosun commented on src/styles/pages/about.module.scss
> +      visibility: hidden;
`visibility: hidden` makes the discord preview invisible, but it still takes up space so it's making the page like randomly long on mobile right now. You can try using `display: none` instead.

2023-07-24 02:57 UTC, raymosun commented on src/styles/pages/about.module.scss
> +    margin-top: 50px;
On this repo we try to use 'rem' instead of 'px' whenever possible for accessibility reasons. I noticed you used 'rem' in most other places so lmk if there was some reason for using 'px' here

2023-07-24 02:57 UTC, raymosun commented on src/styles/pages/about.module.scss
> +      margin: 0 0 0 20px;
Smallest ever nit: you could probably replace this with `margin-left: 20px` 🤓

2023-08-10 07:04 UTC, adahe8 commented on src/styles/pages/about.module.scss
> +      margin: 0 0 0 20px;
fixed! switched to rem as well

2023-08-10 07:04 UTC, adahe8 commented on src/styles/pages/about.module.scss
> +      visibility: hidden;
noted and fixed!

2023-08-17 06:11 UTC, raymosun approved these changes

2023-08-18 05:59 UTC, farisashai approved these changes
I'm going to approve right now to not block the PR completely because the page implementation looks really good. Just some minor code nitpicks to fix though before you merge

2023-08-18 05:59 UTC, farisashai commented on src/pages/about.tsx
> +  const about = `With 100,000 members and 500+ chapters, the Association for Computing
No need to keep this in a variable but not a big deal either way.

2023-08-18 05:59 UTC, farisashai commented on src/pages/about.tsx
> +            <div className={styles.theme}>
Is this div layer necessary or can you just put the className on the <a> tags directly?

2023-08-18 05:59 UTC, farisashai commented on src/pages/about.tsx
> +            acmurl.com
Is there a design reason to write acmurl here instead of acmucsd.com? Could be confusing and harder to find access to the main website possibly.

2023-08-18 05:59 UTC, farisashai commented on src/pages/about.tsx
> +            facebook.com/acm.ucsd
I think `acmurl.com/facebook` works better here and for instagram for consistency with the discord link and because it allows the link to be updated freely through acmurl without a code commit needed. Also slightly easier to read and more memorable.

2023-08-18 05:59 UTC, farisashai commented on src/styles/pages/about.module.scss
> +@use '../vars.scss' as vars;
nit: prefer absolute imports if possible for imports from outside the same directory folder in case things end up moving around

2023-08-18 05:59 UTC, farisashai commented on src/styles/pages/about.module.scss
> +  height: 115;
nit: all css values like this should have units attached for clarity and no ambiguity. units here would be `px` for consistency with how the <Image> component behaves.

2023-08-18 05:59 UTC, farisashai commented on src/styles/pages/about.module.scss
> +  .discordpreview {
```suggestion
  .discordPreview {
```
nitpick: camelcase CSS classes

2023-08-18 05:59 UTC, farisashai commented on src/styles/pages/about.module.scss
> +.header {
![Screenshot 2023-08-17 at 10 46 19 PM](https://github.com/acmucsd/membership-portal-ui-v2/assets/33165426/0cae121a-5fee-42d8-9263-baa185f46ebd)
```suggestion
.header {
padding: 0 2rem;
}
```
nit: can we add the 2rem padding just for the sides to align the image left side with the text content horizontally?

2023-08-18 22:44 UTC, adahe8 commented on src/pages/about.tsx
> +            <div className={styles.theme}>
right you are!

2023-08-18 22:44 UTC, adahe8 commented on src/pages/about.tsx
> +            acmurl.com
nope! I was just copying the links over from the old portal - fixed

2023-08-19 00:20 UTC, merged